option(AMFLOW_WITH_GINAC "Enable the GiNaC/CLN symbolic backend." OFF)
option(AMFLOW_WITH_MPFR "Enable MPFR-backed arbitrary precision wiring." OFF)
option(AMFLOW_WITH_YAML_CPP "Enable yaml-cpp based parsing/emission." OFF)

function(amflow_apply_default_warnings target)
  if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
    target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic)
  elseif(MSVC)
    target_compile_options(${target} PRIVATE /W4)
  endif()
endfunction()

function(amflow_apply_optional_dependencies target)
  if(AMFLOW_WITH_GINAC)
    find_package(GiNaC REQUIRED)
    target_compile_definitions(${target} PRIVATE AMFLOW_HAVE_GINAC=1)
    target_link_libraries(${target} PRIVATE GiNaC::GiNaC)
  endif()

  if(AMFLOW_WITH_MPFR)
    find_package(MPFR REQUIRED)
    target_compile_definitions(${target} PRIVATE AMFLOW_HAVE_MPFR=1)
    target_link_libraries(${target} PRIVATE MPFR::MPFR)
  endif()

  if(AMFLOW_WITH_YAML_CPP)
    find_package(yaml-cpp REQUIRED)
    target_compile_definitions(${target} PRIVATE AMFLOW_HAVE_YAML_CPP=1)
    target_link_libraries(${target} PRIVATE yaml-cpp)
  endif()
endfunction()
